### PR TITLE
tool: init configurable logging

### LINKED ISSUE #55: Ugly backtraces for non-bootspec generations
Lanzatool outputs some intimidating backtraces when it encounters non-bootspec generations. This should be handled more gracefully by having an actionable log messages. Something like "Failed to sign generation X, because it is not bootspec compliant."

```
Installing generation 351
Appending secrets to initrd...
/boot/EFI/BOOT/BOOTX64.EFI already exists, skipping...
/boot/EFI/systemd/systemd-bootx64.efi already exists, skipping...
/boot/EFI/nixos/0n01vj3mq06pc31i2yhxndvhv4kwl2vp-linux-6.1.3-bzImage.efi already exists, skipping...
/boot/EFI/nixos/lzxjx9ykfzhv5c2r4v36v2w7b69yrpc1-initrd-linux-6.1.3-initrd.efi already exists, skipping...
Signing and installing /boot/EFI/Linux/nixos-generation-351.efi...
Successfully installed lanzaboote to '/boot'
Malformed generation: Failed to build generation from link: GenerationLink { version: 350, path: "/nix/var/nix/profiles/system-350-link" }

Caused by:
    0: Failed to read bootspec file
    1: No such file or directory (os error 2)

Stack backtrace:
   0: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
   1: lanzatool::generation::Generation::from_link
   2: lanzatool::install::Installer::install
   3: lanzatool::cli::Cli::call
   4: lanzatool::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal
   8: main
   9: __libc_start_call_main
  10: __libc_start_main_alias_1
  11: _start
Malformed generation: Failed to build generation from link: GenerationLink { version: 349, path: "/nix/var/nix/profiles/system-349-link" }

Caused by:
    0: Failed to read bootspec file
    1: No such file or directory (os error 2)

Stack backtrace:
   0: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
   1: lanzatool::generation::Generation::from_link
   2: lanzatool::install::Installer::install
   3: lanzatool::cli::Cli::call
   4: lanzatool::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal
   8: main
   9: __libc_start_call_main
  10: __libc_start_main_alias_1
  11: _start
'/boot/EFI/nixos/qalw2n6bvbsbvrhz9q9ax82fzxg5xhj0-linux-6.1.2-bzImage.efi' not in use anymore. Removing...
'/boot/EFI/nixos/81r7ygqb3hrzvhqgp0wzm1zmvhj1pzvf-initrd-linux-6.1.2-initrd.efi' not in use anymore. Removing...
'/boot/EFI/nixos/.extra-files' not in use anymore. Removing...
```

### PR DESCRIPTION
**Pull request by nikstur**
Replace `println()` calls with logging at different levels using the `log` crate.

Closes #55 #73

### CODE REVIEW

File: rust/tool/src/logging.rs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+    fn log(&self, record: &Record) {
+        if !self.enabled(record.metadata()) {
+            return;
+        };
+        // Do not write the log if it does not come from this crate.
+        if !lzbt_record(record) {
+            return;
+        }
+        println!("{}", record.args());
```
Comment (blitz) [inline rust/tool/src/logging.rs:30]: Typically logging goes to stderr to avoid buffering log messages. But at that point, you just re-implement [stderrlog](https://docs.rs/stderrlog/0.5.4/stderrlog/). Why not use that? It also gives you the typical Unix behavior of `-v`, `-vv`, `-vvv`.

File: rust/tool/src/signature.rs [hunk 2]
```diff
@@ -61,10 +59,8 @@ impl KeyPair {
             if std::io::stderr().write_all(&output.stderr).is_err() {
                 return false;
             };
-            println!(
-                "Failed to verify signature using sbverify with args `{:?}`",
-                &args
-            );
+            log::info!("Failed to verify signature of {path:?}.");
```
Comment (blitz) [inline rust/tool/src/signature.rs:62]: This sounds like `error!` or at least `warn!`? I mean if this is not an error what is? :) In case of errors, it also makes sense to dump all information required for debugging that you have at hand immediately.

Comment (blitz) [reply rust/tool/src/signature.rs:62]: But maybe the log message should be at the call site of `verify`, otherwise legitimate uses of verify might spam the log?

Comment (nikstur) [reply rust/tool/src/signature.rs:62]: Right now this function is called only to check if the systemd-boot binary is signed or not. There, it should not be `error` because we just update the binary if it not signed (e.g. because you just installed Lanzaboote). So you're right it should be at the call site. Maybe a warning makes more sense than an info. But there is really nothing for the user to do, that's why it maybe should be an info?

File: rust/tool/src/logging.rs (hunk 1 above)
Comment (nikstur) [reply rust/tool/src/logging.rs:30]: Never heard of the stderrlog crate before but it looks good. I'm not too fond of the multiple -vvv flags, since I do not believe that a normal CLI user would be interested in anything besides normal output and debug output. However, since Lanzaboote is not really a normal CLI, as it is only called by a module, we might as well implement all log levels.

**Comment by nikstur** [comment]
Thanks for the review @blitz!

File: rust/tool/src/install.rs [hunk 3]
```diff
@@ -307,7 +315,16 @@ impl Installer {
...
         for (from, to) in paths {
-            if newer_systemd_boot(from, to)? || !&self.key_pair.verify(to) {
+            let newer_systemd_boot_available = newer_systemd_boot(from, to)?;
+            if newer_systemd_boot_available {
+                log::info!("Updating systemd-boot...")
+            };
+            let systemd_boot_is_signed = &self.key_pair.verify(to);
+            if !systemd_boot_is_signed {
+                log::warn!("systemd-boot is not signed. Replacing it with a signed binary...")
+            };
```
Comment (nikstur) [inline rust/tool/src/install.rs:325]: I don't love this. Do you have any idea how to make this more concise?

Comment (blitz) [reply rust/tool/src/install.rs:325]: I think it's good enough. I personally would move it into the `if` statement that does the actual installation, but it doesn't really matter.

**Review by blitz — APPROVED** [review]
Looks good!

**Review by RaitoBezarius — APPROVED** [review]
LGTM! Thanks!
